import java.util.ArrayList;
import java.util.*;

public class Node extends Thread{
	private int id;
	private Coordinate coord; //coordinate of the node in the Unite-Square Area
	private Float radius, prob;
	private int locations;
	private int energy, en_send, en_rec, en_sign;
	private int rand; //randomic int generated by hypervisor for RED protocol
	private ArrayList<Node> neigh = new ArrayList<Node>();
    private Map<Integer, Coordinate> m = new HashMap<Integer, Coordinate>(); //contains the map of the routed nodes coordinate
	private String protocol;
	public Node(){}
	
	public Node(int cont_id, Coordinate coo_in, Float r, Float p, Integer g, Integer e,
			Integer e_send, Integer e_rec, Integer e_sign) {
		id= cont_id;		//the ID for the node
		coord= coo_in;		//coordinates of the node
		radius= r;			//communication radius of the node
		prob=p;				//Probability for a neighbour node to process a location claim
		locations=g;		//number of destination location
		energy=e;			//Total energy for the node
		en_send= e_send;	//Energy spent for sending a message
		en_rec= e_rec;		//Energy spent for receiving a message
		en_sign= e_sign;	//Energy for the signature of a message
	}
	
	public int getNodeId(){
		return id;
	}
	
	public boolean setRand(int x){
		rand=x;
		return true;
	}
	
	public Coordinate getCoord(){
		return coord;
	}
	
	public boolean setProtocol(String s){
			protocol=s;
			return true;
	}
	public void insertNeigh(Node n){
		neigh.add(n);
		System.out.println(this.getNodeId()+ " ha come vicino il nodo "+n.getNodeId());
	}
	
	public void clone(Node fromClone){
		id= fromClone.id;
		radius= fromClone.radius;
		prob= fromClone.prob;
		locations= fromClone.locations;
		energy= fromClone.energy;
		en_send= fromClone.en_send;
		en_rec= fromClone.en_rec;
		en_sign= fromClone.en_sign;
	}
	
	public void setCoordinate(Coordinate cor){
		coord=cor;
	}
	public void locationClaimNeigh(){
		for(int i=0; i<neigh.size();i++ ){
			neigh.get(i).locationClaim(this, id, coord);//chiamo locationclaim per tutti i neighbor
			//Energy spent
			energy=energy-en_send;
		}
	}
	public void locationClaim(Node n,int idclaim,Coordinate c){
		//mettere controllo se ignorare o meno
		energy=energy-en_rec;
		if(m.containsKey(idclaim)) //devo controllare se esiste già questo nodo nella mappa??
			if(m.get(idclaim).equals(c)) //controllo se il nodo che ho in memoria ha la stessa coordinata del precedente claim
			{} //do nothing already present in map
			else
			{} // coordinate di stesso id non corrispondo _ ho trovato il clone?
		else
			m.put(idclaim,c);
	}
	public void run(){
		//fatto//solo per red hypervisord dovrebbe generare un int randomico e renderlo noto a tutti i nodi
		//punto 1 uguale per entrambi i protocolli
		//punto 2 uguale per entrambi i protocolli
		//
		if(protocol=="RED");
		if(protocol=="LSM");
		
	}
}
